const hardList = [
  'es5',
  'es6',
  'Typescript',
  'HTML5',
  'CSS3',
  'SASS',
  'React',
  'React native',
  'redux',
  'node',
  'REST',
  'express',
  'koa',
  'nodemon',
  'CSP',
  'redis',
  'mongoDB',
  'socket.io',
  'regular expressions',
  'event loop',
  'prototype chain',
  'publisher subscriber pattern',
  'singleton pattern',
  'factory pattern',
  'hashes',
  'linked lists',
  'bubble sorting algorithm',
  'binary sorting algorithm',
  'boolean algebra',
  'lambda calculus',
  'RWD',
  'ARIA',
  'cross browser compatibility',
  'XSS',
  'unit tests',
  'integration tests',
  'e2e tests',
  'jest',
  'karma',
  'mocha',
  'enzyme',
  'chai',
  'jasmine',
  'sinon',
  'jsdom',
  'webpack',
  'babel',
  'eslint',
  'heroku',
  'git',
  'npm',
  'Semaphore',
  'Travis',
  'chrome DevTools',
  'memory leaks',
  'material-ui',
  'immutable',
  'lodash',
  'jQuery',
  'bash',
  'Inkscape',
  'svg',
  'Visual Studio Code',
  'touch typing',
];

export default hardList;
